name: Pug Pages

on:
  push:
    branches:
      - app

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Compilers Dependencies
        run: npm install

      - name: Compile Pug
        run: npm run build

      - name: Setup GitHub Pages Config
        uses: actions/configure-pages@v4

      - name: Packaging Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Publish GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
